# Generated by Django 5.0.1 on 2024-01-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='user_domain',
        ),
    ]
