# Generated by Django 5.0.1 on 2024-01-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_user_model_user_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_model',
        ),
    ]
