# Generated by Django 5.0 on 2024-01-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_userlog_delete_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='total_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
