# Generated by Django 4.2.9 on 2024-01-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
